// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKz9eX6doA9YE83xqc9ofx5stmnYAwScY',
    appId: '1:140279637322:web:0917d238aa0d8560e44db3',
    messagingSenderId: '140279637322',
    projectId: 'madrasati-6c976',
    authDomain: 'madrasati-6c976.firebaseapp.com',
    storageBucket: 'madrasati-6c976.firebasestorage.app',
    measurementId: 'G-T4XVFM4PB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4j1c_IiMjn5NWyx5BxpacAjHSeymfVcU',
    appId: '1:140279637322:android:5fca5499f7e34186e44db3',
    messagingSenderId: '140279637322',
    projectId: 'madrasati-6c976',
    storageBucket: 'madrasati-6c976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1MvH1CUEIBXv2Iig0Wl0VgMI2M-gvLuc',
    appId: '1:140279637322:ios:53d0e96a0577f55ce44db3',
    messagingSenderId: '140279637322',
    projectId: 'madrasati-6c976',
    storageBucket: 'madrasati-6c976.firebasestorage.app',
    iosBundleId: 'com.example.madrasatiPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1MvH1CUEIBXv2Iig0Wl0VgMI2M-gvLuc',
    appId: '1:140279637322:ios:53d0e96a0577f55ce44db3',
    messagingSenderId: '140279637322',
    projectId: 'madrasati-6c976',
    storageBucket: 'madrasati-6c976.firebasestorage.app',
    iosBundleId: 'com.example.madrasatiPlus',
  );

}